export const TOOL_VERBS: Record<string, string> = {
  browser: "browsing",
  clarify: "asking",
  create_file: "creating",
  delegate_task: "delegating",
  delete_file: "deleting",
  execute_code: "executing",
  explain_answer: "explaining",
  image_generate: "generating",
  list_files: "listing",
  memory: "remembering",
  patch: "patching",
  query_metric: "querying",
  read_file: "reading",
  run_command: "running",
  run_metric_query: "querying",
  search_code: "searching",
  search_files: "searching",
  terminal: "terminal",
  web_extract: "extracting",
  web_search: "searching",
  write_file: "writing"
};

export const VERBS = [
  "pondering",
  "contemplating",
  "musing",
  "cogitating",
  "ruminating",
  "deliberating",
  "mulling",
  "reflecting",
  "processing",
  "reasoning",
  "analyzing",
  "computing",
  "synthesizing",
  "formulating",
  "brainstorming"
] as const;
