import { frozenEditPlace } from "./consent-units.js"
import { frozenJobNote, isPolicyPath } from "./owner-boundary.js"
import { leaveForOwner } from "./state-machine.js"
import type { ChecklistItem } from "../wizard/contracts/jobs.js"

/** The same deterministic scope decision for detector candidates, plan seeds and runtime backstops. */
export function scopeOwnerJob(item: ChecklistItem, sources: ReadonlyMap<string, string>, appRoot = "."): ChecklistItem {
  if (item.owner === "code" && item.state === "left_for_you" && item.ownerBoundary) return item
  if (item.ownerBoundary?.kind === "restored_unit" || item.jobId === "privacy_paragraph") return item
  if (item.state === "blocked" && item.allow.files.length === 0) return item
  const policy = item.allow.files.find(file => isPolicyPath(file, appRoot, sources))
  if (policy) return leaveForOwner(item, `Not changed by us: ${policy} is a policy page, which is yours.`, { kind: "policy_page", file: policy, line: 1 }).item
  const place = frozenEditPlace(item, sources)
  if (!place) return item
  const saved = item.ownerBoundary
  const sameUnit = saved?.kind === "frozen_unit" && saved.file === place.file && saved.unitHash === place.unit.hash
  // The plan's exact owner instructions are durable facts, not regenerated by the jobs backstop.
  const handoff = sameUnit ? { ...(saved.guard ? { guard: saved.guard } : {}), ...(saved.wiring ? { wiring: saved.wiring } : {}) } : {}
  return leaveForOwner(item, sameUnit && item.note ? item.note : frozenJobNote(item, place), { ...handoff, kind: "frozen_unit", file: place.file, line: place.line, unitHash: place.unit.hash, lineOffset: place.line - place.unit.startLine, unitOrdinal: place.unit.ordinal }).item
}
