// THE SEAM between an r4 fixture and the real CLI: draw one screen exactly the
// way the interactive session draws it, and return the ANSI it prints.
//
// It renders the REAL session (`renderInkInteractiveSessionToString`, the same
// React tree `infinite` mounts), fed the way a turn feeds it: the turn store gets
// the views (`recordTurnView`), a waiting approval becomes a write card
// (`initialPendingConfirmations`), the steps become the tool trail and active
// tools, and the chrome gets what the entry point passes. So every byte compared
// is a byte the session prints, through the Ink bridge (`AnsiLine`) included.
//
// Lanes do NOT edit this file. Each lane's feeding lives in its own file, which
// it changes in the same PR as the session change:
//   feed-chrome.ts  R1  entry props (composer placeholder), boot inventory, top bar data, busy note
//   feed-steps.ts   R2  steps → trail and active tools (start/end, step labels)
//   feed-focus.ts   R3/R4  initial key focus (selected row, opened card)
// What the entry point passes (`sessionProps`, `homeInventory`) is INJECTED by
// the caller from the entry point's exports, never written here.
import type { AnswerViewV1, ToolViewFrameV1 } from "@infinite-os/types";

import type { InSessionConfirmationAction } from "../../../desktop/confirm-in-session.js";
import { recordTurnView, resetTurnState } from "../../app/turn-store.js";
import { renderInkInteractiveSessionToString } from "../../ink/interactive-session.js";
import { chromeProps, type EntrySessionProps, type HomeInventoryBuilder } from "./feed-chrome.js";
import { focusProps } from "./feed-focus.js";
import { feedRunningSteps, turnMessages } from "./feed-steps.js";
import type { R4ScreenFixture, R4Turn } from "./fixtures.js";

export { turnMessages } from "./feed-steps.js";

export interface ScreenOptions {
  cols: number;
  /** Fixed wall clock for the render (ms). */
  now: number;
  /** The entry point's home inventory builder (`index.ts` `homeInventoryData`), injected so this module stays light. */
  homeInventory: HomeInventoryBuilder;
  /** The props the entry point gives the session (`feed-chrome.ts` `ENTRY_SESSION_PROPS` until index.ts exports them). */
  sessionProps: EntrySessionProps;
}

/** The views the turn store holds (every view but a waiting write card, which the session draws as the card). */
export function recordedViews(turn: R4Turn): AnswerViewV1[] {
  return turn.views.filter((view, index) => !(index === turn.pending && view.approval?.kind === "card"));
}

export function renderR4Screen(fixture: R4ScreenFixture, options: ScreenOptions): string {
  resetTurnState();
  const props = {
    columns: options.cols,
    onSubmitLine: async () => ({ messages: [] }),
    ...chromeProps(fixture, options.sessionProps, options.homeInventory),
    ...focusProps(fixture)
  };
  const turn = fixture.turn;
  if (!turn) return renderInkInteractiveSessionToString(props);

  const pending: InSessionConfirmationAction[] = [];
  turn.views.forEach((view, index) => {
    if (index === turn.pending && view.approval?.kind === "card") {
      pending.push({
        turnId: view.approval.turnId ?? "turn_r4",
        confirmationHandle: view.approval.handle ?? `h_r4_${index}`,
        summary: view.approval.title,
        confirmationDetails: view.approval.rows,
        confirmFieldsCapable: true,
        view
      });
      return;
    }
    const frame: ToolViewFrameV1 = { type: "tool.view", stage: "tool", message: view.title, viewId: `r4_${index}`, name: view.tool, view };
    recordTurnView(frame);
  });
  feedRunningSteps(turn, options.now);

  return renderInkInteractiveSessionToString({
    ...props,
    initialMessages: turnMessages(turn),
    initialPendingConfirmations: pending
  });
}
